# Configuration file for pipeline

# Links to dataframes from Jesse's repository: jbloomlab/SARS2-mut-fitness
url_founder: https://raw.githubusercontent.com/jbloomlab/SARS2-mut-fitness/refs/heads/main/results_gisaid_2024-04-24/clade_founder_nts/clade_founder_nts.csv
url_counts: https://media.githubusercontent.com/media/jbloomlab/SARS2-mut-fitness/refs/heads/main/results_gisaid_2024-04-24/expected_vs_actual_mut_counts/expected_vs_actual_mut_counts.csv

# Mapping for grouping clades into clusters
clade_cluster:
  {'ancestral': ['20A', '20B', '20C', '20E', '20G', '21C'],
 '20H': ['20H'],
 '20I': ['20I'],
 '20J': ['20J'],
 '21I': ['21I'],
 '21J': ['21J'],
 '21K': ['21K'],
 'BA.2': ['21L', '22C'],
 '22A-B': ['22A', '22B'],
 'BA.2.75': ['22D', '23C'],
 'XBB': ['22F', '23A', '23B', '23D', '23E', '23F', '23H'],
 'late': ['23I']}

# Orf1ab to Nsp numbering (amino-acid start in Orf1ab) from
# https://github.com/theosanderson/Codon2Nucleotide/blob/main/src/App.js
orf1ab_to_nsps:
  nsp1: [1, 180]
  nsp2: [181, 818]
  nsp3: [819, 2763]
  nsp4: [2764, 3263]
  nsp5 (Mpro): [3264, 3569]
  nsp6: [3570, 3859]
  nsp7: [3860, 3942]
  nsp8: [3943, 4140]
  nsp9: [4141, 4253]
  nsp10: [4254, 4392]
  nsp12 (RdRp): [4393, 5324]
  nsp13: [5325, 5925]
  nsp14: [5926, 6452]
  nsp15: [6453, 6798]
  nsp16: [6799, 7096]

# How to handle nucleotide sites that overlap among sites: exclude them from
# amino-acid fitness estimates or retain those sites in estimates. If retained, estimates
# can be confounded by not knowing which gene the selection is acting on.
gene_overlaps:
  exclude:
    - [ORF1a, ORF1ab]  # 11 sites of overlap near ribosomal frameshifting location
    - [ORF7a, ORF7b]  # 1 site of overlap corresponding to ORF7a stop codon
  retain:
    - [N, ORF9b]  # ORF9b is a 291 out-of-frame overlapping reading frame in N

# Pseudocount for calculating amino-acid fitnesses
fitness_pseudocount: 0.5  